// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/api/models"
)

// BattlePassLootReader is a Reader for the BattlePassLoot structure.
type BattlePassLootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BattlePassLootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBattlePassLootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBattlePassLootOK creates a BattlePassLootOK with default headers values
func NewBattlePassLootOK() *BattlePassLootOK {
	return &BattlePassLootOK{}
}

/*BattlePassLootOK handles this case with default header values.

Battle Pass Loot Response
*/
type BattlePassLootOK struct {
	Payload *models.BattlePassLootResponse
}

func (o *BattlePassLootOK) Error() string {
	return fmt.Sprintf("[GET /loot/title/{title}/platform/{platform}/list/loot_season_{season}/en][%d] battlePassLootOK  %+v", 200, o.Payload)
}

func (o *BattlePassLootOK) GetPayload() *models.BattlePassLootResponse {
	return o.Payload
}

func (o *BattlePassLootOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BattlePassLootResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
