// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCodPointsParams creates a new CodPointsParams object
// with the default values initialized.
func NewCodPointsParams() *CodPointsParams {
	var ()
	return &CodPointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCodPointsParamsWithTimeout creates a new CodPointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCodPointsParamsWithTimeout(timeout time.Duration) *CodPointsParams {
	var ()
	return &CodPointsParams{

		timeout: timeout,
	}
}

// NewCodPointsParamsWithContext creates a new CodPointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCodPointsParamsWithContext(ctx context.Context) *CodPointsParams {
	var ()
	return &CodPointsParams{

		Context: ctx,
	}
}

// NewCodPointsParamsWithHTTPClient creates a new CodPointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCodPointsParamsWithHTTPClient(client *http.Client) *CodPointsParams {
	var ()
	return &CodPointsParams{
		HTTPClient: client,
	}
}

/*CodPointsParams contains all the parameters to send to the API endpoint
for the cod points operation typically these are written to a http.Request
*/
type CodPointsParams struct {

	/*Cookie
	  ACT_SSO_COOKIE required for authenticated requests. Set with the value returned in login

	*/
	Cookie string
	/*Gamertag
	  Gamer tag

	*/
	Gamertag string
	/*LookupType
	  Lookup Type

	*/
	LookupType string
	/*Platform
	  Game platform

	*/
	Platform string
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cod points params
func (o *CodPointsParams) WithTimeout(timeout time.Duration) *CodPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cod points params
func (o *CodPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cod points params
func (o *CodPointsParams) WithContext(ctx context.Context) *CodPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cod points params
func (o *CodPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cod points params
func (o *CodPointsParams) WithHTTPClient(client *http.Client) *CodPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cod points params
func (o *CodPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCookie adds the cookie to the cod points params
func (o *CodPointsParams) WithCookie(cookie string) *CodPointsParams {
	o.SetCookie(cookie)
	return o
}

// SetCookie adds the cookie to the cod points params
func (o *CodPointsParams) SetCookie(cookie string) {
	o.Cookie = cookie
}

// WithGamertag adds the gamertag to the cod points params
func (o *CodPointsParams) WithGamertag(gamertag string) *CodPointsParams {
	o.SetGamertag(gamertag)
	return o
}

// SetGamertag adds the gamertag to the cod points params
func (o *CodPointsParams) SetGamertag(gamertag string) {
	o.Gamertag = gamertag
}

// WithLookupType adds the lookupType to the cod points params
func (o *CodPointsParams) WithLookupType(lookupType string) *CodPointsParams {
	o.SetLookupType(lookupType)
	return o
}

// SetLookupType adds the lookupType to the cod points params
func (o *CodPointsParams) SetLookupType(lookupType string) {
	o.LookupType = lookupType
}

// WithPlatform adds the platform to the cod points params
func (o *CodPointsParams) WithPlatform(platform string) *CodPointsParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the cod points params
func (o *CodPointsParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithTitle adds the title to the cod points params
func (o *CodPointsParams) WithTitle(title string) *CodPointsParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the cod points params
func (o *CodPointsParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *CodPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Cookie
	if err := r.SetHeaderParam("Cookie", o.Cookie); err != nil {
		return err
	}

	// path param gamertag
	if err := r.SetPathParam("gamertag", o.Gamertag); err != nil {
		return err
	}

	// path param lookupType
	if err := r.SetPathParam("lookupType", o.LookupType); err != nil {
		return err
	}

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
