// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/v2/api/models"
)

// CodPointsReader is a Reader for the CodPoints structure.
type CodPointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CodPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCodPointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCodPointsOK creates a CodPointsOK with default headers values
func NewCodPointsOK() *CodPointsOK {
	return &CodPointsOK{}
}

/*CodPointsOK handles this case with default header values.

Call of Duty Points Response
*/
type CodPointsOK struct {
	Payload *models.CodPointsResponse
}

func (o *CodPointsOK) Error() string {
	return fmt.Sprintf("[GET /inventory/v1/title/{title}/platform/{platform}/{lookupType}/{gamertag}/currency][%d] codPointsOK  %+v", 200, o.Payload)
}

func (o *CodPointsOK) GetPayload() *models.CodPointsResponse {
	return o.Payload
}

func (o *CodPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CodPointsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
