// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFullMatchInfoParams creates a new FullMatchInfoParams object
// with the default values initialized.
func NewFullMatchInfoParams() *FullMatchInfoParams {
	var ()
	return &FullMatchInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFullMatchInfoParamsWithTimeout creates a new FullMatchInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFullMatchInfoParamsWithTimeout(timeout time.Duration) *FullMatchInfoParams {
	var ()
	return &FullMatchInfoParams{

		timeout: timeout,
	}
}

// NewFullMatchInfoParamsWithContext creates a new FullMatchInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewFullMatchInfoParamsWithContext(ctx context.Context) *FullMatchInfoParams {
	var ()
	return &FullMatchInfoParams{

		Context: ctx,
	}
}

// NewFullMatchInfoParamsWithHTTPClient creates a new FullMatchInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFullMatchInfoParamsWithHTTPClient(client *http.Client) *FullMatchInfoParams {
	var ()
	return &FullMatchInfoParams{
		HTTPClient: client,
	}
}

/*FullMatchInfoParams contains all the parameters to send to the API endpoint
for the full match info operation typically these are written to a http.Request
*/
type FullMatchInfoParams struct {

	/*GameType
	  Game Type

	*/
	GameType string
	/*MatchID
	  Match ID

	*/
	MatchID string
	/*Platform
	  Game platform

	*/
	Platform string
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the full match info params
func (o *FullMatchInfoParams) WithTimeout(timeout time.Duration) *FullMatchInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the full match info params
func (o *FullMatchInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the full match info params
func (o *FullMatchInfoParams) WithContext(ctx context.Context) *FullMatchInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the full match info params
func (o *FullMatchInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the full match info params
func (o *FullMatchInfoParams) WithHTTPClient(client *http.Client) *FullMatchInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the full match info params
func (o *FullMatchInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGameType adds the gameType to the full match info params
func (o *FullMatchInfoParams) WithGameType(gameType string) *FullMatchInfoParams {
	o.SetGameType(gameType)
	return o
}

// SetGameType adds the gameType to the full match info params
func (o *FullMatchInfoParams) SetGameType(gameType string) {
	o.GameType = gameType
}

// WithMatchID adds the matchID to the full match info params
func (o *FullMatchInfoParams) WithMatchID(matchID string) *FullMatchInfoParams {
	o.SetMatchID(matchID)
	return o
}

// SetMatchID adds the matchId to the full match info params
func (o *FullMatchInfoParams) SetMatchID(matchID string) {
	o.MatchID = matchID
}

// WithPlatform adds the platform to the full match info params
func (o *FullMatchInfoParams) WithPlatform(platform string) *FullMatchInfoParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the full match info params
func (o *FullMatchInfoParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithTitle adds the title to the full match info params
func (o *FullMatchInfoParams) WithTitle(title string) *FullMatchInfoParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the full match info params
func (o *FullMatchInfoParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *FullMatchInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gameType
	if err := r.SetPathParam("gameType", o.GameType); err != nil {
		return err
	}

	// path param matchId
	if err := r.SetPathParam("matchId", o.MatchID); err != nil {
		return err
	}

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
