// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/api/models"
)

// FullMatchInfoReader is a Reader for the FullMatchInfo structure.
type FullMatchInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FullMatchInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFullMatchInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFullMatchInfoOK creates a FullMatchInfoOK with default headers values
func NewFullMatchInfoOK() *FullMatchInfoOK {
	return &FullMatchInfoOK{}
}

/*FullMatchInfoOK handles this case with default header values.

Full Match Info Response
*/
type FullMatchInfoOK struct {
	Payload *models.FullMatchInfoResponse
}

func (o *FullMatchInfoOK) Error() string {
	return fmt.Sprintf("[GET /crm/cod/v2/title/{title}/platform/{platform}/fullMatch/{gameType}/{matchId}/en][%d] fullMatchInfoOK  %+v", 200, o.Payload)
}

func (o *FullMatchInfoOK) GetPayload() *models.FullMatchInfoResponse {
	return o.Payload
}

func (o *FullMatchInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FullMatchInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
