// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/v2/api/models"
)

// GamerLootReader is a Reader for the GamerLoot structure.
type GamerLootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GamerLootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGamerLootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGamerLootOK creates a GamerLootOK with default headers values
func NewGamerLootOK() *GamerLootOK {
	return &GamerLootOK{}
}

/*GamerLootOK handles this case with default header values.

Get Gamer Loot Response
*/
type GamerLootOK struct {
	Payload *models.GamerLootResponse
}

func (o *GamerLootOK) Error() string {
	return fmt.Sprintf("[GET /loot/title/{title}/platform/{platform}/{lookupType}/{gamertag}/status/en][%d] gamerLootOK  %+v", 200, o.Payload)
}

func (o *GamerLootOK) GetPayload() *models.GamerLootResponse {
	return o.Payload
}

func (o *GamerLootOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GamerLootResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
