// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGamerMatchListParams creates a new GamerMatchListParams object
// with the default values initialized.
func NewGamerMatchListParams() *GamerMatchListParams {
	var ()
	return &GamerMatchListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGamerMatchListParamsWithTimeout creates a new GamerMatchListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGamerMatchListParamsWithTimeout(timeout time.Duration) *GamerMatchListParams {
	var ()
	return &GamerMatchListParams{

		timeout: timeout,
	}
}

// NewGamerMatchListParamsWithContext creates a new GamerMatchListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGamerMatchListParamsWithContext(ctx context.Context) *GamerMatchListParams {
	var ()
	return &GamerMatchListParams{

		Context: ctx,
	}
}

// NewGamerMatchListParamsWithHTTPClient creates a new GamerMatchListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGamerMatchListParamsWithHTTPClient(client *http.Client) *GamerMatchListParams {
	var ()
	return &GamerMatchListParams{
		HTTPClient: client,
	}
}

/*GamerMatchListParams contains all the parameters to send to the API endpoint
for the gamer match list operation typically these are written to a http.Request
*/
type GamerMatchListParams struct {

	/*Cookie
	  ACT_SSO_COOKIE required for authenticated requests. Set with the value returned in login

	*/
	Cookie string
	/*End
	  Match end unix timestamp in milliseconds ex. 1608407321000

	*/
	End int64
	/*GameType
	  Game Type

	*/
	GameType string
	/*Gamertag
	  Gamer tag

	*/
	Gamertag string
	/*Limit
	  The numbers of items to return

	*/
	Limit *int32
	/*LookupType
	  Lookup Type

	*/
	LookupType string
	/*Platform
	  Game platform

	*/
	Platform string
	/*Start
	  Match start unix timestamp in milliseconds ex. 1602815242000

	*/
	Start int64
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the gamer match list params
func (o *GamerMatchListParams) WithTimeout(timeout time.Duration) *GamerMatchListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the gamer match list params
func (o *GamerMatchListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the gamer match list params
func (o *GamerMatchListParams) WithContext(ctx context.Context) *GamerMatchListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the gamer match list params
func (o *GamerMatchListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the gamer match list params
func (o *GamerMatchListParams) WithHTTPClient(client *http.Client) *GamerMatchListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the gamer match list params
func (o *GamerMatchListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCookie adds the cookie to the gamer match list params
func (o *GamerMatchListParams) WithCookie(cookie string) *GamerMatchListParams {
	o.SetCookie(cookie)
	return o
}

// SetCookie adds the cookie to the gamer match list params
func (o *GamerMatchListParams) SetCookie(cookie string) {
	o.Cookie = cookie
}

// WithEnd adds the end to the gamer match list params
func (o *GamerMatchListParams) WithEnd(end int64) *GamerMatchListParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the gamer match list params
func (o *GamerMatchListParams) SetEnd(end int64) {
	o.End = end
}

// WithGameType adds the gameType to the gamer match list params
func (o *GamerMatchListParams) WithGameType(gameType string) *GamerMatchListParams {
	o.SetGameType(gameType)
	return o
}

// SetGameType adds the gameType to the gamer match list params
func (o *GamerMatchListParams) SetGameType(gameType string) {
	o.GameType = gameType
}

// WithGamertag adds the gamertag to the gamer match list params
func (o *GamerMatchListParams) WithGamertag(gamertag string) *GamerMatchListParams {
	o.SetGamertag(gamertag)
	return o
}

// SetGamertag adds the gamertag to the gamer match list params
func (o *GamerMatchListParams) SetGamertag(gamertag string) {
	o.Gamertag = gamertag
}

// WithLimit adds the limit to the gamer match list params
func (o *GamerMatchListParams) WithLimit(limit *int32) *GamerMatchListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the gamer match list params
func (o *GamerMatchListParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithLookupType adds the lookupType to the gamer match list params
func (o *GamerMatchListParams) WithLookupType(lookupType string) *GamerMatchListParams {
	o.SetLookupType(lookupType)
	return o
}

// SetLookupType adds the lookupType to the gamer match list params
func (o *GamerMatchListParams) SetLookupType(lookupType string) {
	o.LookupType = lookupType
}

// WithPlatform adds the platform to the gamer match list params
func (o *GamerMatchListParams) WithPlatform(platform string) *GamerMatchListParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the gamer match list params
func (o *GamerMatchListParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithStart adds the start to the gamer match list params
func (o *GamerMatchListParams) WithStart(start int64) *GamerMatchListParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the gamer match list params
func (o *GamerMatchListParams) SetStart(start int64) {
	o.Start = start
}

// WithTitle adds the title to the gamer match list params
func (o *GamerMatchListParams) WithTitle(title string) *GamerMatchListParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the gamer match list params
func (o *GamerMatchListParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *GamerMatchListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Cookie
	if err := r.SetHeaderParam("Cookie", o.Cookie); err != nil {
		return err
	}

	// path param end
	if err := r.SetPathParam("end", swag.FormatInt64(o.End)); err != nil {
		return err
	}

	// path param gameType
	if err := r.SetPathParam("gameType", o.GameType); err != nil {
		return err
	}

	// path param gamertag
	if err := r.SetPathParam("gamertag", o.Gamertag); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	// path param lookupType
	if err := r.SetPathParam("lookupType", o.LookupType); err != nil {
		return err
	}

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param start
	if err := r.SetPathParam("start", swag.FormatInt64(o.Start)); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
