// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGamerStatsParams creates a new GamerStatsParams object
// with the default values initialized.
func NewGamerStatsParams() *GamerStatsParams {
	var ()
	return &GamerStatsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGamerStatsParamsWithTimeout creates a new GamerStatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGamerStatsParamsWithTimeout(timeout time.Duration) *GamerStatsParams {
	var ()
	return &GamerStatsParams{

		timeout: timeout,
	}
}

// NewGamerStatsParamsWithContext creates a new GamerStatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGamerStatsParamsWithContext(ctx context.Context) *GamerStatsParams {
	var ()
	return &GamerStatsParams{

		Context: ctx,
	}
}

// NewGamerStatsParamsWithHTTPClient creates a new GamerStatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGamerStatsParamsWithHTTPClient(client *http.Client) *GamerStatsParams {
	var ()
	return &GamerStatsParams{
		HTTPClient: client,
	}
}

/*GamerStatsParams contains all the parameters to send to the API endpoint
for the gamer stats operation typically these are written to a http.Request
*/
type GamerStatsParams struct {

	/*Cookie
	  ACT_SSO_COOKIE required for authenticated requests. Set with the value returned in login

	*/
	Cookie string
	/*GameType
	  Game Type

	*/
	GameType string
	/*Gamertag
	  Gamer tag

	*/
	Gamertag string
	/*LookupType
	  Lookup Type

	*/
	LookupType string
	/*Platform
	  Game platform

	*/
	Platform string
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the gamer stats params
func (o *GamerStatsParams) WithTimeout(timeout time.Duration) *GamerStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the gamer stats params
func (o *GamerStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the gamer stats params
func (o *GamerStatsParams) WithContext(ctx context.Context) *GamerStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the gamer stats params
func (o *GamerStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the gamer stats params
func (o *GamerStatsParams) WithHTTPClient(client *http.Client) *GamerStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the gamer stats params
func (o *GamerStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCookie adds the cookie to the gamer stats params
func (o *GamerStatsParams) WithCookie(cookie string) *GamerStatsParams {
	o.SetCookie(cookie)
	return o
}

// SetCookie adds the cookie to the gamer stats params
func (o *GamerStatsParams) SetCookie(cookie string) {
	o.Cookie = cookie
}

// WithGameType adds the gameType to the gamer stats params
func (o *GamerStatsParams) WithGameType(gameType string) *GamerStatsParams {
	o.SetGameType(gameType)
	return o
}

// SetGameType adds the gameType to the gamer stats params
func (o *GamerStatsParams) SetGameType(gameType string) {
	o.GameType = gameType
}

// WithGamertag adds the gamertag to the gamer stats params
func (o *GamerStatsParams) WithGamertag(gamertag string) *GamerStatsParams {
	o.SetGamertag(gamertag)
	return o
}

// SetGamertag adds the gamertag to the gamer stats params
func (o *GamerStatsParams) SetGamertag(gamertag string) {
	o.Gamertag = gamertag
}

// WithLookupType adds the lookupType to the gamer stats params
func (o *GamerStatsParams) WithLookupType(lookupType string) *GamerStatsParams {
	o.SetLookupType(lookupType)
	return o
}

// SetLookupType adds the lookupType to the gamer stats params
func (o *GamerStatsParams) SetLookupType(lookupType string) {
	o.LookupType = lookupType
}

// WithPlatform adds the platform to the gamer stats params
func (o *GamerStatsParams) WithPlatform(platform string) *GamerStatsParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the gamer stats params
func (o *GamerStatsParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithTitle adds the title to the gamer stats params
func (o *GamerStatsParams) WithTitle(title string) *GamerStatsParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the gamer stats params
func (o *GamerStatsParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *GamerStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Cookie
	if err := r.SetHeaderParam("Cookie", o.Cookie); err != nil {
		return err
	}

	// path param gameType
	if err := r.SetPathParam("gameType", o.GameType); err != nil {
		return err
	}

	// path param gamertag
	if err := r.SetPathParam("gamertag", o.Gamertag); err != nil {
		return err
	}

	// path param lookupType
	if err := r.SetPathParam("lookupType", o.LookupType); err != nil {
		return err
	}

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
