// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/api/models"
)

// LoadoutReader is a Reader for the Loadout structure.
type LoadoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoadoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLoadoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLoadoutOK creates a LoadoutOK with default headers values
func NewLoadoutOK() *LoadoutOK {
	return &LoadoutOK{}
}

/*LoadoutOK handles this case with default header values.

Loadout Response
*/
type LoadoutOK struct {
	Payload *models.LoadoutResponse
}

func (o *LoadoutOK) Error() string {
	return fmt.Sprintf("[GET /loadouts/v4/title/{title}/items/mode/{gameType}/en][%d] loadoutOK  %+v", 200, o.Payload)
}

func (o *LoadoutOK) GetPayload() *models.LoadoutResponse {
	return o.Payload
}

func (o *LoadoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LoadoutResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
