// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMapListParams creates a new MapListParams object
// with the default values initialized.
func NewMapListParams() *MapListParams {
	var ()
	return &MapListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMapListParamsWithTimeout creates a new MapListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMapListParamsWithTimeout(timeout time.Duration) *MapListParams {
	var ()
	return &MapListParams{

		timeout: timeout,
	}
}

// NewMapListParamsWithContext creates a new MapListParams object
// with the default values initialized, and the ability to set a context for a request
func NewMapListParamsWithContext(ctx context.Context) *MapListParams {
	var ()
	return &MapListParams{

		Context: ctx,
	}
}

// NewMapListParamsWithHTTPClient creates a new MapListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMapListParamsWithHTTPClient(client *http.Client) *MapListParams {
	var ()
	return &MapListParams{
		HTTPClient: client,
	}
}

/*MapListParams contains all the parameters to send to the API endpoint
for the map list operation typically these are written to a http.Request
*/
type MapListParams struct {

	/*GameType
	  Game Type

	*/
	GameType string
	/*Platform
	  Game platform

	*/
	Platform string
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the map list params
func (o *MapListParams) WithTimeout(timeout time.Duration) *MapListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the map list params
func (o *MapListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the map list params
func (o *MapListParams) WithContext(ctx context.Context) *MapListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the map list params
func (o *MapListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the map list params
func (o *MapListParams) WithHTTPClient(client *http.Client) *MapListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the map list params
func (o *MapListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGameType adds the gameType to the map list params
func (o *MapListParams) WithGameType(gameType string) *MapListParams {
	o.SetGameType(gameType)
	return o
}

// SetGameType adds the gameType to the map list params
func (o *MapListParams) SetGameType(gameType string) {
	o.GameType = gameType
}

// WithPlatform adds the platform to the map list params
func (o *MapListParams) WithPlatform(platform string) *MapListParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the map list params
func (o *MapListParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithTitle adds the title to the map list params
func (o *MapListParams) WithTitle(title string) *MapListParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the map list params
func (o *MapListParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *MapListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param gameType
	if err := r.SetPathParam("gameType", o.GameType); err != nil {
		return err
	}

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
