// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/carlocayos/go-cod/api/models"
)

// MatchListReader is a Reader for the MatchList structure.
type MatchListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MatchListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMatchListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMatchListOK creates a MatchListOK with default headers values
func NewMatchListOK() *MatchListOK {
	return &MatchListOK{}
}

/*MatchListOK handles this case with default header values.

Match List Response
*/
type MatchListOK struct {
	Payload *models.GamerAllMatchListResponse
}

func (o *MatchListOK) Error() string {
	return fmt.Sprintf("[GET /crm/cod/v2/title/{title}/platform/{platform}/{lookupType}/{gamertag}/matches/{gameType}/start/{start}/end/{end}][%d] matchListOK  %+v", 200, o.Payload)
}

func (o *MatchListOK) GetPayload() *models.GamerAllMatchListResponse {
	return o.Payload
}

func (o *MatchListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GamerAllMatchListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
