// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPurchasableParams creates a new PurchasableParams object
// with the default values initialized.
func NewPurchasableParams() *PurchasableParams {
	var ()
	return &PurchasableParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPurchasableParamsWithTimeout creates a new PurchasableParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPurchasableParamsWithTimeout(timeout time.Duration) *PurchasableParams {
	var ()
	return &PurchasableParams{

		timeout: timeout,
	}
}

// NewPurchasableParamsWithContext creates a new PurchasableParams object
// with the default values initialized, and the ability to set a context for a request
func NewPurchasableParamsWithContext(ctx context.Context) *PurchasableParams {
	var ()
	return &PurchasableParams{

		Context: ctx,
	}
}

// NewPurchasableParamsWithHTTPClient creates a new PurchasableParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPurchasableParamsWithHTTPClient(client *http.Client) *PurchasableParams {
	var ()
	return &PurchasableParams{
		HTTPClient: client,
	}
}

/*PurchasableParams contains all the parameters to send to the API endpoint
for the purchasable operation typically these are written to a http.Request
*/
type PurchasableParams struct {

	/*Platform
	  Game platform

	*/
	Platform string
	/*Title
	  Game title

	*/
	Title string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the purchasable params
func (o *PurchasableParams) WithTimeout(timeout time.Duration) *PurchasableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the purchasable params
func (o *PurchasableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the purchasable params
func (o *PurchasableParams) WithContext(ctx context.Context) *PurchasableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the purchasable params
func (o *PurchasableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the purchasable params
func (o *PurchasableParams) WithHTTPClient(client *http.Client) *PurchasableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the purchasable params
func (o *PurchasableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPlatform adds the platform to the purchasable params
func (o *PurchasableParams) WithPlatform(platform string) *PurchasableParams {
	o.SetPlatform(platform)
	return o
}

// SetPlatform adds the platform to the purchasable params
func (o *PurchasableParams) SetPlatform(platform string) {
	o.Platform = platform
}

// WithTitle adds the title to the purchasable params
func (o *PurchasableParams) WithTitle(title string) *PurchasableParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the purchasable params
func (o *PurchasableParams) SetTitle(title string) {
	o.Title = title
}

// WriteToRequest writes these params to a swagger request
func (o *PurchasableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param platform
	if err := r.SetPathParam("platform", o.Platform); err != nil {
		return err
	}

	// path param title
	if err := r.SetPathParam("title", o.Title); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
