// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BattlePassLootResponse battle pass loot response
//
// swagger:model battlePassLootResponse
type BattlePassLootResponse struct {

	// data
	Data *BattlePassLootResponseData `json:"data,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// battle pass loot response additional properties
	BattlePassLootResponseAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *BattlePassLootResponse) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// data
		Data *BattlePassLootResponseData `json:"data,omitempty"`

		// status
		Status string `json:"status,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv BattlePassLootResponse

	rcv.Data = stage1.Data
	rcv.Status = stage1.Status
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "data")
	delete(stage2, "status")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.BattlePassLootResponseAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m BattlePassLootResponse) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// data
		Data *BattlePassLootResponseData `json:"data,omitempty"`

		// status
		Status string `json:"status,omitempty"`
	}

	stage1.Data = m.Data
	stage1.Status = m.Status

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.BattlePassLootResponseAdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.BattlePassLootResponseAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this battle pass loot response
func (m *BattlePassLootResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BattlePassLootResponse) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BattlePassLootResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BattlePassLootResponse) UnmarshalBinary(b []byte) error {
	var res BattlePassLootResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BattlePassLootResponseData battle pass loot response data
//
// swagger:model BattlePassLootResponseData
type BattlePassLootResponseData struct {

	// category name
	CategoryName string `json:"categoryName,omitempty"`

	// category title
	CategoryTitle string `json:"categoryTitle,omitempty"`

	// chase
	Chase string `json:"chase,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// tiers
	Tiers map[string]Tier `json:"tiers,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// battle pass loot response data additional properties
	BattlePassLootResponseDataAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *BattlePassLootResponseData) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// category name
		CategoryName string `json:"categoryName,omitempty"`

		// category title
		CategoryTitle string `json:"categoryTitle,omitempty"`

		// chase
		Chase string `json:"chase,omitempty"`

		// message
		Message string `json:"message,omitempty"`

		// tiers
		Tiers map[string]Tier `json:"tiers,omitempty"`

		// type
		Type string `json:"type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv BattlePassLootResponseData

	rcv.CategoryName = stage1.CategoryName
	rcv.CategoryTitle = stage1.CategoryTitle
	rcv.Chase = stage1.Chase
	rcv.Message = stage1.Message
	rcv.Tiers = stage1.Tiers
	rcv.Type = stage1.Type
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "categoryName")
	delete(stage2, "categoryTitle")
	delete(stage2, "chase")
	delete(stage2, "message")
	delete(stage2, "tiers")
	delete(stage2, "type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.BattlePassLootResponseDataAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m BattlePassLootResponseData) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// category name
		CategoryName string `json:"categoryName,omitempty"`

		// category title
		CategoryTitle string `json:"categoryTitle,omitempty"`

		// chase
		Chase string `json:"chase,omitempty"`

		// message
		Message string `json:"message,omitempty"`

		// tiers
		Tiers map[string]Tier `json:"tiers,omitempty"`

		// type
		Type string `json:"type,omitempty"`
	}

	stage1.CategoryName = m.CategoryName
	stage1.CategoryTitle = m.CategoryTitle
	stage1.Chase = m.Chase
	stage1.Message = m.Message
	stage1.Tiers = m.Tiers
	stage1.Type = m.Type

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.BattlePassLootResponseDataAdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.BattlePassLootResponseDataAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this battle pass loot response data
func (m *BattlePassLootResponseData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BattlePassLootResponseData) validateTiers(formats strfmt.Registry) error {

	if swag.IsZero(m.Tiers) { // not required
		return nil
	}

	for k := range m.Tiers {

		if swag.IsZero(m.Tiers[k]) { // not required
			continue
		}
		if val, ok := m.Tiers[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BattlePassLootResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BattlePassLootResponseData) UnmarshalBinary(b []byte) error {
	var res BattlePassLootResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// Tier tier
//
// swagger:model Tier
type Tier struct {

	// description body
	DescriptionBody string `json:"descriptionBody,omitempty"`

	// description title
	DescriptionTitle string `json:"descriptionTitle,omitempty"`

	// exclusive title
	ExclusiveTitle string `json:"exclusiveTitle,omitempty"`

	// free
	Free string `json:"free,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// image detail
	ImageDetail string `json:"imageDetail,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// rarity
	Rarity string `json:"rarity,omitempty"`

	// tier
	Tier string `json:"tier,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this tier
func (m *Tier) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tier) UnmarshalBinary(b []byte) error {
	var res Tier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
