// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GamerAllMatchListResponse gamer all match list response
//
// swagger:model gamerAllMatchListResponse
type GamerAllMatchListResponse struct {

	// data
	Data []*GamerAllMatchListResponseDataItems0 `json:"data"`

	// status
	Status string `json:"status,omitempty"`

	// gamer all match list response additional properties
	GamerAllMatchListResponseAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *GamerAllMatchListResponse) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// data
		Data []*GamerAllMatchListResponseDataItems0 `json:"data"`

		// status
		Status string `json:"status,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv GamerAllMatchListResponse

	rcv.Data = stage1.Data
	rcv.Status = stage1.Status
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "data")
	delete(stage2, "status")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.GamerAllMatchListResponseAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m GamerAllMatchListResponse) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// data
		Data []*GamerAllMatchListResponseDataItems0 `json:"data"`

		// status
		Status string `json:"status,omitempty"`
	}

	stage1.Data = m.Data
	stage1.Status = m.Status

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.GamerAllMatchListResponseAdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.GamerAllMatchListResponseAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this gamer all match list response
func (m *GamerAllMatchListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GamerAllMatchListResponse) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {
		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {
			if err := m.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GamerAllMatchListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GamerAllMatchListResponse) UnmarshalBinary(b []byte) error {
	var res GamerAllMatchListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GamerAllMatchListResponseDataItems0 gamer all match list response data items0
//
// swagger:model GamerAllMatchListResponseDataItems0
type GamerAllMatchListResponseDataItems0 struct {

	// map
	Map string `json:"map,omitempty"`

	// match Id
	MatchID string `json:"matchId,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// gamer all match list response data items0 additional properties
	GamerAllMatchListResponseDataItems0AdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *GamerAllMatchListResponseDataItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// map
		Map string `json:"map,omitempty"`

		// match Id
		MatchID string `json:"matchId,omitempty"`

		// platform
		Platform string `json:"platform,omitempty"`

		// timestamp
		Timestamp int64 `json:"timestamp,omitempty"`

		// title
		Title string `json:"title,omitempty"`

		// type
		Type string `json:"type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv GamerAllMatchListResponseDataItems0

	rcv.Map = stage1.Map
	rcv.MatchID = stage1.MatchID
	rcv.Platform = stage1.Platform
	rcv.Timestamp = stage1.Timestamp
	rcv.Title = stage1.Title
	rcv.Type = stage1.Type
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "map")
	delete(stage2, "matchId")
	delete(stage2, "platform")
	delete(stage2, "timestamp")
	delete(stage2, "title")
	delete(stage2, "type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.GamerAllMatchListResponseDataItems0AdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m GamerAllMatchListResponseDataItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// map
		Map string `json:"map,omitempty"`

		// match Id
		MatchID string `json:"matchId,omitempty"`

		// platform
		Platform string `json:"platform,omitempty"`

		// timestamp
		Timestamp int64 `json:"timestamp,omitempty"`

		// title
		Title string `json:"title,omitempty"`

		// type
		Type string `json:"type,omitempty"`
	}

	stage1.Map = m.Map
	stage1.MatchID = m.MatchID
	stage1.Platform = m.Platform
	stage1.Timestamp = m.Timestamp
	stage1.Title = m.Title
	stage1.Type = m.Type

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.GamerAllMatchListResponseDataItems0AdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.GamerAllMatchListResponseDataItems0AdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this gamer all match list response data items0
func (m *GamerAllMatchListResponseDataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GamerAllMatchListResponseDataItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GamerAllMatchListResponseDataItems0) UnmarshalBinary(b []byte) error {
	var res GamerAllMatchListResponseDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
